trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.x'
  storageAccountName: 'myazurethingblob01'  # Your Azure storage account name
  containerName: 'myazurethingcontainer01'  # Your Azure blob container name
  localPathToFile: '$(Build.ArtifactStagingDirectory)/output.zip'
  blobName: 'output.txt'  # The path inside the blob container

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true
  displayName: 'Set up Python $(pythonVersion)'

- script: |
    python file.py
  displayName: 'Run Python Script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'output.txt'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
    includeRootFolder: false
  displayName: 'Archive output'

# Ensure the file exists and set correct permissions
- script: |
    if [ ! -f "$(localPathToFile)" ]; then
      echo "Error: File $(localPathToFile) not found."
      exit 1
    fi
    chmod +x $(localPathToFile)  # Give the file executable permissions just in case
    echo "File $(localPathToFile) exists, permissions set, proceeding with upload."
  displayName: 'Check file existence and set permissions'

# Upload the file to Azure Blob Storage using Azure CLI
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Blob'  # Reference to your Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Uploading $(localPathToFile) to Azure Blob Storage..."
      az storage blob upload --account-name $(storageAccountName) \
                             --container-name $(containerName) \
                             --name $(blobName) \
                             --file $(localPathToFile) \
                             --auth-mode login \
                             --output table
  displayName: 'Upload output to Azure Blob Storage'
